const GAMES = [
{id:"neon-core",name:"Neon Core: Orbital Defense",category:"Arcade",icon:"assets/game-icons/neon-core.svg",url:"games/neon-core/",emoji:"🎯",c1:"#00ffff",c2:"#ff0055",popular:86,available:true,badge:"Neon Defense",description:"Defend the core from incoming threats with orbital auto-fire.",tags:"arcade defense neon reflex canvas"},
{id:"neon-catch",name:"Neon Catch: Void Edition",category:"Arcade",icon:"assets/game-icons/neon-catch.svg",url:"games/neon-catch/",emoji:"💠",c1:"#00ffff",c2:"#ff0055",popular:84,available:true,badge:"Fast Reflex",description:"Catch falling targets, survive the void, and beat your high score.",tags:"arcade reflex neon catch survival"},
{id:"neon-void",name:"Neon Void",category:"Arcade",icon:"assets/game-icons/neon-void.svg",url:"games/neon-void/",emoji:"🪐",c1:"#00ffff",c2:"#ff0055",popular:82,available:true,badge:"Grapple",description:"Grapple between neon orbs and survive the deadly void.",tags:"arcade grapple neon action survival"},
{id:"neon-rise",name:"Neon Rise",category:"Arcade",icon:"assets/game-icons/neon-rise.svg",url:"games/neon-rise/",emoji:"⬆️",c1:"#00ffff",c2:"#ff0055",popular:80,available:true,badge:"Platformer",description:"Ascend through the void, stack shields, and chase high scores.",tags:"arcade platformer neon jump action"},
{id:"neon-breaker",name:"Neon Breaker",category:"Arcade",icon:"assets/game-icons/neon-breaker.svg",url:"games/neon-breaker/",emoji:"🧱",c1:"#a020f0",c2:"#00ffff",popular:78,available:true,badge:"Sandbox Mode",description:"Break glowing bricks with classic, hard, and sandbox modes.",tags:"arcade breakout sandbox neon puzzle"},
{id:"pixel-sandbox",name:"Pixel Sandbox",category:"Simulation",icon:"assets/game-icons/pixel-sandbox.png",url:"games/pixel-sandbox/",emoji:"🧪",c1:"#182033",c2:"#36c2a1",popular:100,available:true,badge:"500 elements"},
{id:"iron-snout",name:"Iron Snout",category:"Arcade",icon:"assets/game-icons/iron-snout.png",url:"games/iron-snout/",emoji:"🐷",c1:"#ff7a18",c2:"#e91e63",popular:88,available:true,badge:"HTML5 Arcade",description:"Fast-paced pig vs wolves arcade fighting.",tags:"arcade action fighting reflex"},
{id:"eaglercraft-1-12-2",name:"Eaglercraft 1.12.2",category:"Sandbox",icon:"assets/game-icons/eaglercraft-1-12-2.png",url:"games/eaglercraft-1-12-2/",emoji:"⛏️",c1:"#4f8f3a",c2:"#9bd26b",popular:99,available:true,badge:"Heavy Game",description:"Play Eaglercraft 1.12.2 in your browser with worlds saved locally.",tags:"minecraft sandbox survival eaglercraft"},
];